"""empty message

Revision ID: 74a161fa9ba9
Revises: 3c08986c8bfe
Create Date: 2022-08-03 22:18:28.567379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a161fa9ba9'
down_revision = '3c08986c8bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('todolists', 'nqme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('nqme', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('todolists', 'name')
    # ### end Alembic commands ###
